import test from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import User from '../src/models/User.js';
import Group from '../src/models/Group.js';
import GroupMember from '../src/models/GroupMember.js';
import Notification from '../src/models/Notification.js';
import { inviteByEmail } from '../src/controllers/groupController.js';
import { respondToInvite, getNotifications, markAllAsRead, deleteNotification, deleteReadNotifications } from '../src/controllers/notificationController.js';
let db;
const response = () => ({ code: 200, status(n) { this.code = n; return this; }, json(body) { this.body = body; return this; } });
test.before(async () => { db = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(db.getUri()); await GroupMember.init(); });
test.after(async () => { await mongoose.disconnect(); await db.stop(); });
test('Invitations are private, validate registered emails, and can only be accepted once by the recipient', async () => {
 const owner = await User.create({ name: 'Owner', email: 'owner@test.com', password: 'secret123' });
 const recipient = await User.create({ name: 'Recipient', email: 'recipient@test.com', password: 'secret123' });
 const group = await Group.create({ name: 'Team', ownerId: owner._id });
 const req = { params: { groupId: group._id }, body: { email: ' RECIPIENT@TEST.COM ' }, user: owner, group };
 const sent = response(); await inviteByEmail(req, sent); assert.equal(sent.code, 200);
 assert.equal(await GroupMember.countDocuments({ userId: recipient._id }), 0);
 const duplicate = response(); await inviteByEmail(req, duplicate); assert.equal(duplicate.code, 409);
 const unknown = response(); await inviteByEmail({ ...req, body: { email: 'missing@test.com' } }, unknown); assert.equal(unknown.code, 404);
 const invalid = response(); await inviteByEmail({ ...req, body: {} }, invalid); assert.equal(invalid.code, 400);
 const note = await Notification.findOne({ userId: recipient._id });
 const privateList = response(); await getNotifications({ user: owner }, privateList); assert.equal(privateList.body.data.notifications.length, 0);
 const respondReq = { params: { id: note._id }, body: { action: 'accept' }, user: recipient };
 const forbidden = response(); await respondToInvite({ ...respondReq, user: owner }, forbidden); assert.equal(forbidden.code, 400);
 const accepted = response(); await respondToInvite(respondReq, accepted); assert.equal(accepted.code, 200);
 const repeat = response(); await respondToInvite(respondReq, repeat); assert.equal(repeat.code, 400);
 assert.equal(await GroupMember.countDocuments({ userId: recipient._id, groupId: group._id }), 1);
 const saved = await Notification.findById(note._id); assert.equal(saved.data.status, 'accepted'); assert.equal(saved.isRead, true);
});
test('Reading or declining does not join; deleted groups cannot be accepted', async () => {
 const recipient = await User.findOne({ email: 'recipient@test.com' });
 const owner = await User.findOne({ email: 'owner@test.com' });
 const group = await Group.create({ name: 'Another team', ownerId: owner._id });
 const note = await Notification.create({ userId: recipient._id, type: 'invite', title: 'Invitation', message: 'Join', data: { groupId: group._id } });
 await markAllAsRead({ user: recipient }, response());
 const declined = response(); await respondToInvite({ params: { id: note._id }, user: recipient, body: { action: 'decline' } }, declined); assert.equal(declined.code, 200);
 assert.equal(await GroupMember.countDocuments({ groupId: group._id }), 0);
 const second = await Notification.create({ userId: recipient._id, type: 'invite', title: 'Invitation', message: 'Join', data: { groupId: group._id } });
 group.deletedAt = new Date(); await group.save();
 const deleted = response(); await respondToInvite({ params: { id: second._id }, user: recipient, body: { action: 'accept' } }, deleted); assert.equal(deleted.code, 400);
 assert.equal(await GroupMember.countDocuments({ groupId: group._id }), 0);
});

test('Notification deletion is scoped to the recipient and clearing read preserves pending invites', async () => {
 const user = await User.findOne({ email: 'recipient@test.com' });
 const other = await User.findOne({ email: 'owner@test.com' });
 await Notification.deleteMany({});
 const make = (extra = {}) => Notification.create({ userId: user._id, title: 'Notice', message: 'Details', ...extra });
 const read = await make({ isRead: true });
 const unread = await make();
 const handled = await make({ isRead: true, type: 'invite', data: { status: 'declined' } });
 const pending = await make({ isRead: true, type: 'invite' });
 const foreign = await make({ userId: other._id, isRead: true });
 const denied = response();
 await deleteNotification({ user: other, params: { id: unread._id } }, denied);
 assert.equal(denied.code, 404);
 assert.ok(await Notification.findById(unread._id));
 const invalid = response();
 await deleteNotification({ user, params: { id: 'bad-id' } }, invalid);
 assert.equal(invalid.code, 400);
 const cleared = response(); await deleteReadNotifications({ user }, cleared);
 assert.equal(cleared.code, 200); assert.equal(cleared.body.data.deletedCount, 2);
 assert.equal(await Notification.findById(read._id), null);
 assert.equal(await Notification.findById(handled._id), null);
 assert.ok(await Notification.findById(pending._id));
 assert.ok(await Notification.findById(foreign._id));
 const deleted = response(); await deleteNotification({ user, params: { id: unread._id } }, deleted);
 assert.equal(deleted.code, 200);
 const list = response(); await getNotifications({ user }, list);
 assert.equal(list.body.data.unreadCount, 0);
 assert.deepEqual(list.body.data.notifications.map(n => String(n._id)), [String(pending._id)]);
});
